# Generated by Django 4.1.2 on 2022-10-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_status_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='color',
        ),
        migrations.AddField(
            model_name='type',
            name='color',
            field=models.CharField(default='#000', max_length=7, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
